### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'asscalar'

### ISSUE THREAD

**Issue by douglatornell** [SalishSeaCast/tools#70]
After updating `numpy` in `nowcast-env` on `skookum` from 1.22.3 to 1.24.0:

```python-traceback
2022-12-21 12:26:38,380 CRITICAL [make_feeds] unhandled exception:
Traceback (most recent call last):
  File "/SalishSeaCast/NEMO_Nowcast/nemo_nowcast/worker.py", line 391, in _do_work
    checklist = self.worker_func(
  File "/SalishSeaCast/SalishSeaNowcast/nowcast/workers/make_feeds.py", line 90, in make_feeds
    max_ssh_info = _calc_max_ssh_risk(feed, run_date, run_type, config)
  File "/SalishSeaCast/SalishSeaNowcast/nowcast/workers/make_feeds.py", line 210, in _calc_max_ssh_risk
    max_ssh, max_ssh_time = _calc_max_ssh(feed, ttide, run_date, run_type, config)
  File "/SalishSeaCast/SalishSeaNowcast/nowcast/workers/make_feeds.py", line 227, in _calc_max_ssh
    ssh_ts = nc_tools.ssh_timeseries_at_point(grid_T_15m, 0, 0, datetimes=True)
  File "/SalishSeaCast/tools/SalishSeaTools/salishsea_tools/nc_tools.py", line 357, in ssh_timeseries_at_point
    time = timestamp(grid_T, range(len(ssh)), time_var=time_var)
  File "/SalishSeaCast/tools/SalishSeaTools/salishsea_tools/nc_tools.py", line 270, in timestamp
    results.append(time_orig + timedelta(seconds=np.asscalar(time_counter[i])))
  File "/SalishSeaCast/nowcast-env/lib/python3.10/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'asscalar'
```

**Comment by douglatornell** [comment]
From https://numpy.org/doc/1.21/reference/generated/numpy.asscalar.html:

> `numpy.asscalar(a)` has been deprecated since version 1.16: use `numpy.ndarray.item()` instead.

**Comment by douglatornell** [comment]
There are 4 instances for `numpy.asscalar()` in SalishSeaTools:

* `geo_tools.py` line 215
* `geo_tools.py` line 229
* `nc_tools.py` line 270
* `wind_tools.py` line 258

**Comment by douglatornell** [comment]
At least 1 more instance masquerading as `np.asscalar()`:

```python-traceback
2022-12-22 10:39:28,259 CRITICAL [make_plots] unhandled exception:
Traceback (most recent call last):
  File "/SalishSeaCast/NEMO_Nowcast/nemo_nowcast/worker.py", line 391, in _do_work
    checklist = self.worker_func(
  File "/SalishSeaCast/SalishSeaNowcast/nowcast/workers/make_plots.py", line 322, in make_plots
    checklist = _render_figures(
  File "/SalishSeaCast/SalishSeaNowcast/nowcast/workers/make_plots.py", line 1035, in _render_figures
    fig = _calc_figure(fig_func, args, kwargs)
  File "/SalishSeaCast/SalishSeaNowcast/nowcast/workers/make_plots.py", line 1102, in _calc_figure
    fig = fig_func(*args, **kwargs)
  File "/SalishSeaCast/SalishSeaNowcast/nowcast/figures/comparison/compare_venus_ctd.py", line 69, in make_figure
    plot_data = _prep_plot_data(
  File "/SalishSeaCast/SalishSeaNowcast/nowcast/figures/comparison/compare_venus_ctd.py", line 91, in _prep_plot_data
    model_time = nc_tools.timestamp(
  File "/SalishSeaCast/tools/SalishSeaTools/salishsea_tools/nc_tools.py", line 270, in timestamp
    results.append(time_orig + timedelta(seconds=np.asscalar(time_counter[i])))
  File "/SalishSeaCast/nowcast-env/lib/python3.10/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'asscalar'
```

**Comment by douglatornell** [comment]
Reopening was a false alarm. I had forgotten to pull yesterday's update into the `skookum:nowcast-env` environment.
