### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'float'

### ISSUE THREAD

**Issue by douglatornell** [SalishSeaCast/tools#72]
After updating `numpy` in `nowcast-env` environment from 1.22.3 to 1.24.0:

```python-traceback
2022-12-22 07:26:14,218 CRITICAL [make_live_ocean_files] unhandled exception:
Traceback (most recent call last):
  File "/SalishSeaCast/NEMO_Nowcast/nemo_nowcast/worker.py", line 391, in _do_work
    checklist = self.worker_func(
  File "/SalishSeaCast/SalishSeaNowcast/nowcast/workers/make_live_ocean_files.py", line 82, in make_live_ocean_files
    filepaths = create_LiveOcean_TS_BCs(
  File "/SalishSeaCast/tools/SalishSeaTools/salishsea_tools/LiveOcean_BCs.py", line 605, in create_LiveOcean_TS_BCs
    interpl = stabilize(sigmal, interpl)
  File "/SalishSeaCast/tools/SalishSeaTools/salishsea_tools/LiveOcean_BCs.py", line 238, in stabilize
    interps['salt'][:k+1, i, j] += -add_salt/np.float(k+1)
  File "/SalishSeaCast/nowcast-env/lib/python3.10/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'
```
